---
# image: node:8-alpine

before_script:
  - export ROOT=`pwd`

  # prepare needed software (not applicable for shell executor)
  # - sudo apt-get update -y
  # - sudo apt-get install -y python git openssh-client curl build-essential
  - sudo npm i -g npm
  - node -v
  - npm -v

cache:
  untracked: true
  key: "GOALIFY-CHAT-SERVER-V1"
  paths:
    - $ROOT/node_modules
    - $ROOT/.meteor/local
    - $ROOT/packages/rocketchat-livechat/.npm
    - $ROOT/packages/rocketchat-livechat/.app/node_modules
    - $ROOT/packages/rocketchat-livechat/.app/.meteor/local

stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  only:
    - develop
  script:
    - npm install
    - npm run lint
    - npm run testunit
    - npm run stylelint

build_job:
  stage: build
  only:
    - goalify
    - test-gitlab-ci
  script:
    # Install meteor VM (not applicable for shell executor)
    # - if [ ! -e "/usr/local/bin/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
    - meteor --version
    - meteor npm install
    - mkdir -p ~/tmp/build
    - meteor build --server-only ~/tmp/build
  artifacts:
    paths:
      - ~/tmp/build/*.gz

deploy_job:
  stage: deploy
  only:
    - goalify
    - test-gitlab-ci
  script:
    # install aws CLI to do S3 deploy
    - pip install awscli --upgrade --user
